import '@/ui/styles/global.css';
import { MainLayout } from '@/ui/layouts/main-layout';
import { ThemeProvider } from '@/ui/contexts/theme-context';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <MainLayout>{children}</MainLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
